/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 12 20:21:14 2016. */

#include "commands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Request_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Request, Command, Command, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, Request, Profile, Command, &ReflowProfile_fields),
    PB_LAST_FIELD
};

const pb_field_t ReflowProfile_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ReflowProfile, StartRate, StartRate, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, SoakTemp1, StartRate, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, SoakTemp2, SoakTemp1, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, SoakLen, SoakTemp2, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, PeakTemp, SoakLen, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, TimeToPeak, PeakTemp, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, CoolRate, TimeToPeak, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, ReflowProfile, Preheat, CoolRate, 0),
    PB_LAST_FIELD
};

const pb_field_t ProfileStage_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, ProfileStage, State, State, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ProfileStage, ReflowTimer, State, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ProfileStage, TargetTemp, ReflowTimer, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ProfileStage, TcTemp, TargetTemp, 0),
    PB_LAST_FIELD
};

const pb_field_t Response_fields[7] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Response, Result, Result, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, Response, Type, Result, 0),
    PB_ONEOF_FIELD(payload,   3, INT32   , ONEOF, STATIC  , OTHER, Response, TcState, Type, 0),
    PB_ONEOF_FIELD(payload,   4, MESSAGE , ONEOF, STATIC  , OTHER, Response, Stage, Type, &ProfileStage_fields),
    PB_ONEOF_FIELD(payload,   5, ENUM    , ONEOF, STATIC  , OTHER, Response, ErrorCode, Type, 0),
    PB_ONEOF_FIELD(payload,   6, MESSAGE , ONEOF, STATIC  , OTHER, Response, Profile, Type, &ReflowProfile_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Request, Profile) < 65536 && pb_membersize(Response, payload.Stage) < 65536 && pb_membersize(Response, payload.Profile) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Request_ReflowProfile_ProfileStage_Response)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Request, Profile) < 256 && pb_membersize(Response, payload.Stage) < 256 && pb_membersize(Response, payload.Profile) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Request_ReflowProfile_ProfileStage_Response)
#endif


/* @@protoc_insertion_point(eof) */
