/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Sat Oct 15 18:31:50 2016. */

#ifndef PB_COMMANDS_PB_H_INCLUDED
#define PB_COMMANDS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Request_RequestType {
    Request_RequestType_NONE = 0,
    Request_RequestType_STARTPROFILE = 1,
    Request_RequestType_STOPPROFILE = 2,
    Request_RequestType_GETPROFILESTAGE = 3,
    Request_RequestType_GETPROFILE = 4,
    Request_RequestType_SETPROFILE = 5,
    Request_RequestType_TCSTATE = 6,
    Request_RequestType_RELAYON = 7,
    Request_RequestType_RELAYOFF = 8,
    Request_RequestType_PING = 9,
    Request_RequestType_SETPID = 10,
    Request_RequestType_GETPID = 11
} Request_RequestType;
#define _Request_RequestType_MIN Request_RequestType_NONE
#define _Request_RequestType_MAX Request_RequestType_GETPID
#define _Request_RequestType_ARRAYSIZE ((Request_RequestType)(Request_RequestType_GETPID+1))

typedef enum _ProfileStage_ProfileStageState {
    ProfileStage_ProfileStageState_STOP = 0,
    ProfileStage_ProfileStageState_START = 1,
    ProfileStage_ProfileStageState_SOAK = 2,
    ProfileStage_ProfileStageState_PEAK = 3,
    ProfileStage_ProfileStageState_COOL = 4,
    ProfileStage_ProfileStageState_PREHEAT = 5
} ProfileStage_ProfileStageState;
#define _ProfileStage_ProfileStageState_MIN ProfileStage_ProfileStageState_STOP
#define _ProfileStage_ProfileStageState_MAX ProfileStage_ProfileStageState_PREHEAT
#define _ProfileStage_ProfileStageState_ARRAYSIZE ((ProfileStage_ProfileStageState)(ProfileStage_ProfileStageState_PREHEAT+1))

typedef enum _Response_ResultType {
    Response_ResultType_SUCCESS = 0,
    Response_ResultType_FAIL = 1
} Response_ResultType;
#define _Response_ResultType_MIN Response_ResultType_SUCCESS
#define _Response_ResultType_MAX Response_ResultType_FAIL
#define _Response_ResultType_ARRAYSIZE ((Response_ResultType)(Response_ResultType_FAIL+1))

typedef enum _Response_ResponseType {
    Response_ResponseType_STARTPROFILE = 0,
    Response_ResponseType_STOPPROFILE = 1,
    Response_ResponseType_GETPROFILESTAGE = 2,
    Response_ResponseType_GETPROFILE = 3,
    Response_ResponseType_SETPROFILE = 4,
    Response_ResponseType_TCSTATE = 5,
    Response_ResponseType_RELAYON = 6,
    Response_ResponseType_RELAYOFF = 7,
    Response_ResponseType_PING = 8,
    Response_ResponseType_SETPID = 10,
    Response_ResponseType_GETPID = 11
} Response_ResponseType;
#define _Response_ResponseType_MIN Response_ResponseType_STARTPROFILE
#define _Response_ResponseType_MAX Response_ResponseType_GETPID
#define _Response_ResponseType_ARRAYSIZE ((Response_ResponseType)(Response_ResponseType_GETPID+1))

typedef enum _Response_CycleStatus {
    Response_CycleStatus_RUNNING = 0,
    Response_CycleStatus_STOPPED = 1,
    Response_CycleStatus_FINISHED = 2
} Response_CycleStatus;
#define _Response_CycleStatus_MIN Response_CycleStatus_RUNNING
#define _Response_CycleStatus_MAX Response_CycleStatus_FINISHED
#define _Response_CycleStatus_ARRAYSIZE ((Response_CycleStatus)(Response_CycleStatus_FINISHED+1))

typedef enum _Response_ErrorCodeType {
    Response_ErrorCodeType_UNKNOWNCOMMAND = 0,
    Response_ErrorCodeType_DECODEFAILED = 1,
    Response_ErrorCodeType_PROFILERUNNING = 2,
    Response_ErrorCodeType_OVENABOVETEMP = 3
} Response_ErrorCodeType;
#define _Response_ErrorCodeType_MIN Response_ErrorCodeType_UNKNOWNCOMMAND
#define _Response_ErrorCodeType_MAX Response_ErrorCodeType_OVENABOVETEMP
#define _Response_ErrorCodeType_ARRAYSIZE ((Response_ErrorCodeType)(Response_ErrorCodeType_OVENABOVETEMP+1))

/* Struct definitions */
typedef struct _Pid {
    int32_t kp;
    int32_t ki;
    int32_t kd;
/* @@protoc_insertion_point(struct:Pid) */
} Pid;

typedef struct _ProfileStage {
    ProfileStage_ProfileStageState State;
    int32_t ReflowTimer;
    int32_t TargetTemp;
    int32_t TcTemp;
/* @@protoc_insertion_point(struct:ProfileStage) */
} ProfileStage;

typedef struct _ReflowProfile {
    int32_t StartRate;
    int32_t SoakTemp1;
    int32_t SoakTemp2;
    int32_t SoakLen;
    int32_t PeakTemp;
    int32_t TimeToPeak;
    int32_t CoolRate;
    int32_t Preheat;
/* @@protoc_insertion_point(struct:ReflowProfile) */
} ReflowProfile;

typedef struct _Request {
    Request_RequestType Command;
    bool has_Profile;
    ReflowProfile Profile;
    bool has_PidGains;
    Pid PidGains;
/* @@protoc_insertion_point(struct:Request) */
} Request;

typedef struct _Response {
    Response_ResultType Result;
    Response_ResponseType Type;
    pb_size_t which_payload;
    union {
        int32_t TcState;
        ProfileStage Stage;
        Response_ErrorCodeType ErrorCode;
        ReflowProfile Profile;
        Pid PidGains;
    } payload;
/* @@protoc_insertion_point(struct:Response) */
} Response;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Request_init_default                     (Request){(Request_RequestType)0, false, ReflowProfile_init_default}
#define Pid_init_default                         {0, 0, 0}
#define ReflowProfile_init_default               {0, 0, 0, 0, 0, 0, 0, 0}
#define ProfileStage_init_default                {(ProfileStage_ProfileStageState)0, 0, 0, 0}
#define Response_init_default                    (Response){(Response_ResultType)0, (Response_ResponseType)0, 0, {0}}
#define Request_init_zero                        {(Request_RequestType)0, false, ReflowProfile_init_zero}
#define Pid_init_zero                            {0, 0, 0}
#define ReflowProfile_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0}
#define ProfileStage_init_zero                   {(ProfileStage_ProfileStageState)0, 0, 0, 0}
#define Response_init_zero                       {(Response_ResultType)0, (Response_ResponseType)0, 0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define Pid_kp_tag                               1
#define Pid_ki_tag                               2
#define Pid_kd_tag                               3
#define ProfileStage_State_tag                   1
#define ProfileStage_ReflowTimer_tag             2
#define ProfileStage_TargetTemp_tag              3
#define ProfileStage_TcTemp_tag                  4
#define ReflowProfile_StartRate_tag              1
#define ReflowProfile_SoakTemp1_tag              2
#define ReflowProfile_SoakTemp2_tag              3
#define ReflowProfile_SoakLen_tag                4
#define ReflowProfile_PeakTemp_tag               5
#define ReflowProfile_TimeToPeak_tag             6
#define ReflowProfile_CoolRate_tag               7
#define ReflowProfile_Preheat_tag                8
#define Request_Command_tag                      1
#define Request_Profile_tag                      2
#define Request_PidGains_tag                     3
#define Response_TcState_tag                     3
#define Response_Stage_tag                       4
#define Response_ErrorCode_tag                   5
#define Response_Profile_tag                     6
#define Response_PidGains_tag                    7
#define Response_Result_tag                      1
#define Response_Type_tag                        2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Request_fields[4];
extern const pb_field_t Pid_fields[4];
extern const pb_field_t ReflowProfile_fields[9];
extern const pb_field_t ProfileStage_fields[5];
extern const pb_field_t Response_fields[8];

/* Maximum encoded size of messages (where known) */
#define Request_size                             127
#define Pid_size                                 33
#define ReflowProfile_size                       88
#define ProfileStage_size                        35
#define Response_size                            94

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COMMANDS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
